version: '3'
services:
  ms_product:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms_product
    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/mysql