version: '3'
services:
  ms_client:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms_client
    ports:
      - "5431:5432"
    volumes:
      - ./db:/var/lib/mysql